"use client";

import { FormEvent, useState } from "react";
import { KeyRound, ShieldCheck, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { ErrorState, LoadingState } from "@/components/ui/states";
import { useAuth } from "@/lib/auth";
import { NotificationPreferencesCard } from "@/components/notifications/notification-preferences";

export default function SettingsPage() {
  const { user, isLoading, logout, fetchWithAuth } = useAuth();
  const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [confirm, setConfirm] = useState("");
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function changePassword(event: FormEvent) { event.preventDefault(); setError(""); setMessage(""); if (next !== confirm) { setError("New password and confirmation must match."); return; } if (next.length < 8) { setError("New password must contain at least 8 characters."); return; } setSaving(true); try { const response = await fetchWithAuth("/api/v1/auth/password-change", { method: "POST", body: JSON.stringify({ current_password: current, new_password: next }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail || "Password change failed."); setMessage(body.message || "Password changed. Sign in again to continue."); setTimeout(() => { void logout(); }, 1200); } catch (reason) { setError(reason instanceof Error ? reason.message : "Password change failed."); } finally { setSaving(false); } }
  if (isLoading) return <LoadingState label="Loading account settings…" />;
  if (!user) return <ErrorState title="Unable to load settings" description="Your session is unavailable. Please sign in again." />;
  const scope = [user.jurisdiction.state_code && `State: ${user.jurisdiction.state_code}`, user.jurisdiction.district_code && `District: ${user.jurisdiction.district_code}`, user.jurisdiction.constituency && `Constituency: ${user.jurisdiction.constituency}`].filter(Boolean);
  return <><PageHeader eyebrow="Account and access" title="Settings" description="Review your account scope and keep your credentials current." /><section className="grid max-w-4xl gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><UserRound className="h-5 w-5 text-sky-700" />Account profile</CardTitle><CardDescription>Identity and jurisdiction information is managed by an authorised administrator.</CardDescription></CardHeader><CardContent className="space-y-4 text-sm"><Info label="Name" value={user.full_name} /><Info label="Email" value={user.email} /><Info label="Role" value={user.role.replaceAll("_", " ")} /><Info label="Jurisdiction" value={scope.length ? scope.join(" · ") : "All assigned jurisdictions"} /></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="h-5 w-5 text-sky-700" />Change password</CardTitle><CardDescription>Changing your password signs out all active sessions.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={changePassword}><label className="grid gap-1.5 text-sm font-medium text-slate-700">Current password<Input required type="password" autoComplete="current-password" value={current} onChange={(event) => setCurrent(event.target.value)} /></label><label className="grid gap-1.5 text-sm font-medium text-slate-700">New password<Input required minLength={8} type="password" autoComplete="new-password" value={next} onChange={(event) => setNext(event.target.value)} /></label><label className="grid gap-1.5 text-sm font-medium text-slate-700">Confirm new password<Input required minLength={8} type="password" autoComplete="new-password" value={confirm} onChange={(event) => setConfirm(event.target.value)} /></label>{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}{message && <p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}<Button type="submit" disabled={saving}>{saving ? "Updating…" : "Update password"}</Button></form></CardContent></Card></section><NotificationPreferencesCard /><Card className="mt-6 max-w-4xl"><CardContent className="flex gap-3 p-5"><ShieldCheck className="h-5 w-5 shrink-0 text-emerald-700" /><p className="text-sm leading-6 text-slate-600">Access is role and jurisdiction scoped. Sensitive investigation content, private evidence, and citizen contact data are restricted to authorised workflows.</p></CardContent></Card></>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 capitalize text-slate-900">{value}</p></div>; }
